# Generated by Django 4.2 on 2023-10-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.department'),
        ),
    ]
