# Generated by Django 4.2 on 2023-10-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_semester_count_alter_semester_semester_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semester_count'),
        ),
    ]
