# Generated by Django 4.2 on 2023-10-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0005_alter_semester_semester_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='attendence',
        ),
    ]
