# Generated by Django 4.2 on 2023-10-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0007_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
