# Generated by Django 4.2 on 2023-10-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0008_remove_attendance_date_remove_attendance_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
