# Generated by Django 4.2 on 2023-10-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0009_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semester')),
            ],
        ),
    ]
