# Generated by Django 4.2 on 2023-10-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0011_student_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Semester',
            new_name='semester',
        ),
    ]
