# Generated by Django 4.2 on 2023-10-30 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0014_rename_attendance_attendance_total_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterWiseAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.AddField(
            model_name='attendence',
            name='sem_wise_attendence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.semesterwiseattendence'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semester_count'),
        ),
        migrations.AddField(
            model_name='student',
            name='attendence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.attendence'),
        ),
    ]
