# Generated by Django 4.2 on 2023-10-31 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0015_attendence_semesterwiseattendence_delete_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.camarks')),
            ],
        ),
        migrations.CreateModel(
            name='EachSubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semesterwisesubject')),
            ],
        ),
        migrations.AddField(
            model_name='camarks',
            name='each_subject_marks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.eachsubjectmarks'),
        ),
    ]
