# Generated by Django 4.2 on 2023-10-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0016_camarks_marks_eachsubjectmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camarks',
            name='each_subject_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='ca_exam',
        ),
        migrations.AddField(
            model_name='camarks',
            name='each_subject_marks',
            field=models.ManyToManyField(to='module1.eachsubjectmarks'),
        ),
        migrations.AddField(
            model_name='marks',
            name='ca_exam',
            field=models.ManyToManyField(to='module1.camarks'),
        ),
    ]
