# Generated by Django 4.2 on 2023-10-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0017_remove_camarks_each_subject_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camarks',
            old_name='each_subject_marks',
            new_name='eachsubjectmarks',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='ca_exam',
            new_name='caexam',
        ),
    ]
