# Generated by Django 4.2 on 2023-11-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0018_rename_each_subject_marks_camarks_eachsubjectmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eachsubjectmarks',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='caexam',
        ),
        migrations.DeleteModel(
            name='CAMarks',
        ),
        migrations.DeleteModel(
            name='EachSubjectMarks',
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
