# Generated by Django 4.2 on 2023-11-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0019_remove_eachsubjectmarks_subject_remove_marks_caexam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caexam', models.ManyToManyField(to='module1.camarks')),
            ],
        ),
        migrations.CreateModel(
            name='EachSubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semesterwisesubject')),
            ],
        ),
        migrations.AddField(
            model_name='camarks',
            name='eachsubjectmarks',
            field=models.ManyToManyField(to='module1.eachsubjectmarks'),
        ),
    ]
