# Generated by Django 4.2 on 2023-11-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0020_camarks_marks_eachsubjectmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='sem_wise_attendence',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='total_count',
        ),
        migrations.RenameModel(
            old_name='SemesterWiseAttendence',
            new_name='DailyAttendence',
        ),
        migrations.CreateModel(
            name='TeacherWiseAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('dailyattendence', models.ManyToManyField(to='module1.dailyattendence')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='attendence',
            name='teacherwiseattendence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.teacherwiseattendence'),
        ),
    ]
