# Generated by Django 4.2 on 2023-11-02 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0021_remove_attendence_sem_wise_attendence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyAttendence',
            new_name='SemesterWiseAttendence',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='teacherwiseattendence',
        ),
        migrations.AddField(
            model_name='attendence',
            name='sem_wise_attendence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.semesterwiseattendence'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TeacherWiseAttendence',
        ),
    ]
