# Generated by Django 4.2 on 2023-11-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0024_teacher_is_hod_alter_student_attendence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='head_of_department',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.department'),
        ),
        migrations.AddField(
            model_name='routinecell',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.department'),
        ),
        migrations.AddField(
            model_name='routinecell',
            name='sem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.semester'),
        ),
    ]
