# Generated by Django 4.2 on 2023-11-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0025_head_of_department_department_routinecell_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='routine',
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.teacher'),
        ),
        migrations.CreateModel(
            name='SemesterTeacherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.department')),
                ('semwisesub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semesterwisesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.teacher')),
            ],
        ),
    ]
