# Generated by Django 4.2 on 2023-11-15 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module1', '0026_remove_teacher_routine_dailyroutine_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='camarks',
            old_name='eachsubjectmarks',
            new_name='each_subject_marks',
        ),
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='dailyroutine',
            new_name='daily_routine',
        ),
        migrations.RenameField(
            model_name='marks',
            old_name='caexam',
            new_name='ca_exam',
        ),
        migrations.RenameField(
            model_name='routinecell',
            old_name='sem',
            new_name='semester',
        ),
        migrations.RemoveField(
            model_name='eachsubjectmarks',
            name='subject',
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyroutine',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SemesterTeacherData',
        ),
        migrations.AddField(
            model_name='teachersubjectroutine',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.dailyroutine'),
        ),
        migrations.AddField(
            model_name='teachersubjectroutine',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semester'),
        ),
        migrations.AddField(
            model_name='teachersubjectroutine',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eachsubjectmarks',
            name='subject_routine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.teachersubjectroutine'),
        ),
    ]
