# Generated by Django 4.2 on 2023-11-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0027_teachersubjectroutine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='daily_routine',
            new_name='routine_cell',
        ),
        migrations.RenameField(
            model_name='teachersubjectroutine',
            old_name='routine',
            new_name='daily_routine',
        ),
        migrations.RemoveField(
            model_name='routinecell',
            name='department',
        ),
        migrations.RemoveField(
            model_name='routinecell',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='teachersubjectroutine',
            name='semester',
        ),
        migrations.AlterField(
            model_name='dailyroutine',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.teacher'),
        ),
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.student'),
        ),
        migrations.AlterField(
            model_name='teachersubjectroutine',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherSemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.semesterwisesubject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='routinecell',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.teachersemestersubject'),
        ),
    ]
