# Generated by Django 4.2 on 2023-11-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0028_rename_daily_routine_dailyroutine_routine_cell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='sem_wise_sub',
        ),
        migrations.RemoveField(
            model_name='semesterwisesubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='semesterwisesubject',
            name='subject',
            field=models.ManyToManyField(to='module1.subject'),
        ),
    ]
