# Generated by Django 4.2 on 2023-11-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0029_remove_semester_sem_wise_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersemestersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.subject'),
        ),
    ]
