# Generated by Django 4.2 on 2023-11-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0030_alter_teachersemestersubject_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyroutine',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='eachsubjectmarks',
            name='subject_routine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.teachersemestersubject'),
        ),
        migrations.DeleteModel(
            name='TeacherSubjectRoutine',
        ),
        migrations.AddField(
            model_name='semesterroutine',
            name='daily_routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module1.dailyroutine'),
        ),
        migrations.AddField(
            model_name='semesterroutine',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.semester'),
        ),
    ]
