# Generated by Django 4.2 on 2023-11-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0031_semesterroutine_remove_dailyroutine_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterroutine',
            name='daily_routine',
        ),
        migrations.AddField(
            model_name='semesterroutine',
            name='daily_routine',
            field=models.ManyToManyField(to='module1.dailyroutine'),
        ),
    ]
