# Generated by Django 4.2 on 2023-11-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0032_remove_semesterroutine_daily_routine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eachsubjectmarks',
            name='exam_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eachsubjectmarks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.student'),
        ),
    ]
