# Generated by Django 4.2 on 2023-11-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0033_eachsubjectmarks_exam_name_eachsubjectmarks_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eachsubjectmarks',
            old_name='subject_routine',
            new_name='subject_name',
        ),
    ]
