# Generated by Django 4.2 on 2023-11-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0034_rename_subject_routine_eachsubjectmarks_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.student'),
        ),
    ]
