# Generated by Django 4.2 on 2023-11-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0035_camarks_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='camarks',
            name='exam_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
