# Generated by Django 4.2 on 2023-11-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0036_camarks_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendence',
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.student'),
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='teacherwiseattendence',
        ),
        migrations.AddField(
            model_name='attendence',
            name='teacherwiseattendence',
            field=models.ManyToManyField(to='module1.teacherwiseattendence'),
        ),
    ]
