# Generated by Django 4.2 on 2023-11-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0037_remove_student_attendence_attendence_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='semester',
        ),
        migrations.AddField(
            model_name='teacherwiseattendence',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module1.semester_count'),
        ),
    ]
