# Generated by Django 4.2 on 2023-11-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("module1", "0040_address_parentdetails_student_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="module1.address",
            ),
        ),
    ]
